### ISSUE TITLE
2.0: LocaleProvider

### ISSUE THREAD

**Issue by yuu2lee4** [FE-Driver/vue-beauty#137]

**Comment by assigeo** [comment]
@yuu2lee4 hello. Happy new year!
I'm interested about your project.
Is there any way that I can help to develop quickly?

**Comment by yuu2lee4** [comment]
@assigeo happy new year,Thank your attention to this project,We welcome any contributions.our  top task right now is developing components based on vue2. Maybe you can fork this project, and switch to next branch, when you want to contributed code, you can assign one component which be labeled 'task' to you in the issue list and labeled it to 'developing'.after you finish one component,Just pull a request.if have any question,You can send email to my email address yuu2lee4@qq.com.

**Comment by yuu2lee4** [comment]
done
