### ISSUE TITLE
官方网站内容有误

### ISSUE THREAD

**Issue by mengkeys** [FE-Driver/vue-beauty#139]
官方网站页面链接：[https://fe-driver.github.io/vue-beauty/#!/components/start](https://fe-driver.github.io/vue-beauty/#!/components/start)

> 代码引用

```js
 //import css
import from 'vue-beauty/style/vue-beauty.min.css'

//import components
import vue-beauty from 'vue-beauty'
Vue.use(vue-beauty)
```

> 遇到的问题
- 无法加载`vue-beauty.min.css`样式文件
- Vue.use(vue-beauty) `vue-beauty`中的`-`为非法字符

> 解决办法
- 修改css文件路径为
```js
import 'vue-beauty/package/style/bue-beauty.min.css'
```
- 修改vue-beauty => VueBeauty

**Comment by mengkeys** [comment]
在项目README.md中看到正确的代码了，但还是系统修改一下官方文档中的问题。

**Comment by yuu2lee4** [comment]
收到。。。
