### ISSUE TITLE
select如何初始化已有的数据

### ISSUE THREAD

**Issue by ISCLOUDX** [FE-Driver/vue-beauty#146]
有一个下拉菜单，其中所有的选项是异步获取得到的，已存在选择的数据也是异步获取的
比如选项[1，2，3] 初始化时，选项为 [ ] 空数组，已选择的结果也为空。
异步获取数据后，得到选项options [1 , 2 , 3] ,已选择的结果为[ 1 ]。
但是此时组件显示的状态依旧为无任何选中，请问这种情况如何处理呢？

**Comment by yuu2lee4** [comment]
也就是说你先初始化了select组件 然后再异步获取数据后才去赋值的？  这确实是select没考虑到的方面，你可以暂时先改为或取到数据后再去初始化select组件
