### ISSUE TITLE
How to customize theme?

### ISSUE THREAD

**Issue by kirtangajjar** [FE-Driver/vue-beauty#158]
here's how antd for react does this - https://ant.design/docs/react/customize-theme.

Is similar thing possible for vue-beauty?

**Comment by yuu2lee4** [comment]
We use ant-design‘s less file，but not support customize theme,you can try and we welcome pr.

**Comment by Preen** [comment]
+1

**Comment by baohouse** [comment]
This is just personal notes, but assuming your app uses webpack for bundling, I think the way to achieve this is to rely on variable substitution `modifyVars` option through the `less-loader`. You just need to pass in a hash where the keys are the name of the variables, and the values is the value you want to use for that variable.

**webpack.config.js**
```
{
  loader: 'less-loader',
  options: {
    javascriptEnabled: true,
    modifyVars: require('./vue-beauty-override.json')
  }
}
```

**vue-beauty-override.json**
```
{
  "@font-size-base": "14px",
  "@btn-height-base": "33px",
  "@btn-height-lg": "38px",
  "@btn-height-sm": "26px",
  "@input-height-base": "33px",
  "@input-height-lg": "38px",
  "@input-height-sm": "26px"
}
```

Then we'd just have to import components like this:
```
// Always import vue-beauty.css first so that the following LESS files can override them
import 'vue-beauty/package/style/vue-beauty.css';

import 'vue-beauty/vb/style/core/index.less';
import 'vue-beauty/vb/components/button/style/index.less';
import 'vue-beauty/vb/components/form/style/index.less';
import 'vue-beauty/vb/components/grid/style/index.less';
import 'vue-beauty/vb/components/input/style/index.less';

import Vue from 'vue';
import vueBeauty from 'vue-beauty';

Vue.use(vueBeauty);
```

**Comment by sumaolin** [comment]
[ant-design 自定义主题 custom theme 的文档 webpack中配置说明 ](https://github.com/ant-design/ant-design/issues/8027)
