### ISSUE TITLE
How to use layout component?

### ISSUE THREAD

**Issue by kirtangajjar** [FE-Driver/vue-beauty#159]
Can we use [layout component](https://ant.design/components/layout/) in vue-beauty?

**Comment by kirtangajjar** [comment]
@yuu2lee4 I see you have just added the layout component. Can you please update the NPM repository so that I can update my project

**Comment by kirtangajjar** [comment]
For some reason i'm not able to use `v-layout`, let me check, if it's any bug in library, i'll report it here.

**Comment by yuu2lee4** [comment]
@kirtangajjar  Already  updated.Please see version 0.1.0.

**Comment by kirtangajjar** [comment]
got it 👍
