### ISSUE TITLE
using v-slider throws error

### ISSUE THREAD

**Issue by kirtangajjar** [FE-Driver/vue-beauty#160]
I tried to use recently added `v-layout` code. `v-layout`, `v-header`, `v-content` and `v-footer` works fine however, I was unable to use `v-slider`. 

When I tried to use `v-slider` it threw error.
Here is the screenshot of error from Chrome Developer Console - 
![screen shot 2017-02-23 at 2 58 09 pm](https://cloud.githubusercontent.com/assets/8456197/23252943/a547f788-f9d8-11e6-8bb2-2b5e7278c586.png)
And here is where the error seems to come from - 
![screen shot 2017-02-23 at 3 01 42 pm](https://cloud.githubusercontent.com/assets/8456197/23253041/16ae4634-f9d9-11e6-872a-b0673534eb65.png)
Note that on right hand side, in "scope" tab, the value of this is null.

I was able to trace back the error to [tooltip.js](https://github.com/FE-Driver/vue-beauty/blob/master/vb/directive/tooltip.js#L28) file. Somehow, the value of `this` is null when it checks for `this.arg === 'focus'`

I am using 0.1.0 version from npm. If you need any additional details, inform me, and i will give them to you

**Comment by kirtangajjar** [comment]
Checkout my project code at - https://github.com/kirtangajjar/vue-beauty-bug-sample

**Comment by kirtangajjar** [comment]
@yuu2lee4 Have you checked it out? The cause of error might be http://stackoverflow.com/questions/9822561/why-is-this-in-an-anonymous-function-undefined-when-using-strict

**Comment by yuu2lee4** [comment]
I will check it in next monday.

**Comment by yuu2lee4** [comment]
Im sorry to tell you that the npm package of vue-beauty is based on vue1.0, the version based on vue2.0 is developing in branch next,and we may realese a npm version that you can install it like `npm install vue-beauty@next` .

**Comment by kirtangajjar** [comment]
@yuu2lee4 How many things are left to do for vue 2.0 in `next` branch?

**Comment by yuu2lee4** [comment]
![image](https://cloud.githubusercontent.com/assets/8046366/23362335/3b68b270-fd30-11e6-9a12-1e5546138710.png)
I will release it this week.

**Comment by kirtangajjar** [comment]
@yuu2lee4 Can you please publish the next branch on npm? I want to use it in my project and I am waiting for it since this monday.

**Comment by yuu2lee4** [comment]
sorry for forgeting that,you can clone this repertory to your local and switch to next branch,then you can import it to your  project manually.

**Comment by kirtangajjar** [comment]
@yuu2lee4 I will do that, but I also need to share it with my team so an npm branch is more preferable. Any idea on how much more time it will take to publish `next` branch on `npm`

**Comment by yuu2lee4** [comment]
Ok,i will do it next week.

**Comment by kirtangajjar** [comment]
@yuu2lee4 I was cloning the next branch and realized that there was no `package` folder in it as it is in `master` branch. Also the `webpack.package.config.js` and related `dev` and `prod` configuration script are not present.

So how can I build the project and get the `vue-beauty.js`, so I can use it in my project?

**Comment by yuu2lee4** [comment]
you can use it like this:
import '../../vue-beauty/vb/style/index.less';
import vueBeauty from '../../vue-beauty/vb';
if you use webpack2,you need push vue-beauty/node_modules into resolve.modules and let babel-loader to transform vue-beauty.
My configuration is like this:
![image](https://cloud.githubusercontent.com/assets/8046366/23585997/52f478ca-01c7-11e7-94c9-c18684936ae9.png)

**Comment by kirtangajjar** [comment]
I tried following your steps, so here's my configuration file. 

![screen shot 2017-03-05 at 5 28 17 pm](https://cloud.githubusercontent.com/assets/8456197/23587261/2d6ba27a-01ce-11e7-9874-639c4443fa05.png)

It gives me following error - 
```
ERROR in ./static/vue-beauty/vb/index.js
Module build failed: Error: Couldn't find preset "latest" relative to directory "/Applications/XAMPP/xamppfiles/htdocs/dwda/static/vue-beauty"
    at /Applications/XAMPP/xamppfiles/htdocs/dwda/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Applications/XAMPP/xamppfiles/htdocs/dwda/node_modules/babel-core/lib/transformation/file/options/option-manager.js
:275:20)
    at OptionManager.mergePresets (/Applications/XAMPP/xamppfiles/htdocs/dwda/node_modules/babel-core/lib/transformation/file/options/option-manager.js:2
64:10)
    at OptionManager.mergeOptions (/Applications/XAMPP/xamppfiles/htdocs/dwda/node_modules/babel-core/lib/transformation/file/options/option-manager.js:2
49:14)
    at OptionManager.init (/Applications/XAMPP/xamppfiles/htdocs/dwda/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Applications/XAMPP/xamppfiles/htdocs/dwda/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Applications/XAMPP/xamppfiles/htdocs/dwda/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Applications/XAMPP/xamppfiles/htdocs/dwda/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Applications/XAMPP/xamppfiles/htdocs/dwda/node_modules/babel-loader/lib/index.js:46:20)
    at Object.module.exports (/Applications/XAMPP/xamppfiles/htdocs/dwda/node_modules/babel-loader/lib/index.js:134:16)
 @ ./src/main.js 3:0-48
```

Any idea why? 
Also it would be great if you could upload `webpack.package.config.js` on `next` branch.

**Comment by yuu2lee4** [comment]
you must execute `npm install` in vue-beauty's  and i suggest you put the directory out from your project.

**Comment by kirtangajjar** [comment]
@yuu2lee4 Thanks for the tip, it solved the above error, but now i'm getting this - 

```
These relative modules were not found:

* ../../vue-beauty/vb/style/index.less in ./src/main.js
* ./style/index.less in ../vue-beauty/vb/components/alert/index.js, ../vue-beauty/vb/components/breadcrumb/index.js and 30 others
* ./style/steps.less in ../vue-beauty/vb/components/steps/index.js
* ./style/inputNumber.less in ../vue-beauty/vb/components/inputNumber/index.js
```

I checked it, and the vue-beauty project is placed in parent folder of my project root. Hence, everything should work fine. Also, looks like webpack has trouble finding style of individual components in each folder.

**Comment by yuu2lee4** [comment]
everything works fine in my project,I need more infomation

**Comment by kirtangajjar** [comment]
@yuu2lee4 done. Turns out I needed `less-loader` in dev-dependendencies.

**Comment by kirtangajjar** [comment]
@yuu2lee4 Did you have time to publish the next branch to npm?

**Comment by yuu2lee4** [comment]
now you can use `npm install vue-beauty@beta -S` OR `yarn add vue-beauty@beta` to use it.

**Comment by kirtangajjar** [comment]
@yuu2lee4 Thanks 👍

**Comment by yuu2lee4** [comment]
update import way:
1、clone this project，switch to next branch;
2、install dependencies(yarn or npm install)，and run  `npm run package`;
3、import to your project:
````javascript
import 'relativePath/vue-beauty/package/style/vue-beauty.min.css';
import vueBeauty from 'relativePath/vue-beauty';

vue.use(vueBeauty);
````
when you want update vue-beauty,you just need run `git pull` and repeat step 2.
