### ISSUE TITLE
现在 2.0 有没有 npm 的安装方法？

### ISSUE THREAD

**Issue by fish-ball** [FE-Driver/vue-beauty#162]
例如说发布一个支持这样的版本号？

```
npm i -S vue-beauty@next
```

**Comment by yuu2lee4** [comment]
目前没有。。。这两天我看看。。。

**Comment by yuu2lee4** [comment]
您可以通过 npm install vue-beauty@beta -S OR yarn add vue-beauty@beta 来体验vue2.0的组件库，但不推荐在生产环境使用。

**Comment by fish-ball** [comment]
谢谢

**Comment by yuu2lee4** [comment]
看一下next分支的readme。。。安装方式更新了
