### ISSUE TITLE
Cascader 级联选择 popupContainer属性怎么填

### ISSUE THREAD

**Issue by 1994crazyboy** [FE-Driver/vue-beauty#163]
下拉菜单渲染父节点，这个function类型怎么填呢？比如我要渲染在<div id="mydiv"></div>这个父节点下，那么是不是这样填呢？
<v-cascader size="large" :options="options" :popupContainer="document.getElementById('mydiv')"></v-cascader>

**Comment by 1994crazyboy** [comment]
父节点：“<div id='mydiv'></div>”
要渲染在父节点下的话是不是这样写呢？
“<v-cascader size="large" :options="gxDiming" :popupContainer="document.getElementById('static')"></v-cascader>
”

**Comment by 1994crazyboy** [comment]
`父节点：“<div id='mydiv'></div>”
要渲染在父节点下的话是不是这样写呢？
“<v-cascader size="large" :options="gxDiming" :popupContainer="document.getElementById('static')"></v-cascader>
”`

**Comment by yuu2lee4** [comment]
`
function(){
     return document.getElementById('static');
}
`

**Comment by 1994crazyboy** [comment]
是这样写么？但是好像还是不行 `<v-cascader size="large" :options="gxDiming" :popupContainer="function(){ return document.getElementById('static'); }" ></v-cascader>`

**Comment by yuu2lee4** [comment]
<v-cascader size="large" :options="gxDiming" :popup-container="function(){ return document.getElementById('static'); }" ></v-cascader>  
驼峰式的prop在html里面要写成横线式的。。html对大小写不敏感
