### ISSUE TITLE
Datatable 表格 获取数据不成功

### ISSUE THREAD

**Issue by 1994crazyboy** [FE-Driver/vue-beauty#164]
参照代码写的，但是提示报错，json数据是网上的数据。保存到本地上了。
地址放在： webapp/data/test.json
然后参数这样写：
el: '#app',
        data: {
            url: "data/test.json",
            columns: [{
                title: "姓名",
                field: 'name',
                sort: true
            },
......(接下来的都是和例子的一样。)

**控制台报错如下：**
vue-beauty.min.js:13 Uncaught (in promise) TypeError: Cannot read property 'get' of undefined
    at VDatatable.<anonymous>

**Comment by yuu2lee4** [comment]
1、你大小写换成横线式的么？
2、你的项目要引入vue-resource0.9.3(这个是我们这边的问题，之后我们会去掉对此的依赖)

**Comment by 1994crazyboy** [comment]
好的，谢谢，已经解决了。
