### ISSUE TITLE
2.0 Datepicker 日期选择器选择时间的话通过 v-on:change 和 v-on:input 均无法返回时间，只有日期

### ISSUE THREAD

**Issue by fish-ball** [FE-Driver/vue-beauty#186]

**Comment by yuu2lee4** [comment]
在我这儿没问题啊。。。你确定开启showtime模式了？

**Comment by fish-ball** [comment]
实际测试日期控件还是有问题的：

1. 选择日期：清除选择之后重新选择日期，会报错；
2. 时间选择：小时应该是 00-23 而不是 01-24，分钟应该是 00-59 而不是 01-60
3. 如果时间为 0，点开之后默认的选择时间按钮是灰色，需要点一下日期才能选择
4. 日期格式配置如果指定时间格式的话会产生错乱

**Comment by fish-ball** [comment]
#187

**Comment by fish-ball** [comment]
@yuu2lee4 这些我已经修改并且提交 Pull Request，请审查合并

#193 #194
