### ISSUE TITLE
2.0: RadioGroup 实现的接口与文档不符

### ISSUE THREAD

**Issue by fish-ball** [FE-Driver/vue-beauty#188]
https://fe-driver.github.io/vue-beauty/#!/components/radio

文档写的选项用 radios: [{text, name}] 传入，实际是用 data: [{text, value}] 传入

**Comment by yuu2lee4** [comment]
这是1.0的文档。。。2.0你自己在本地看。。

**Comment by fish-ball** [comment]
哦。。额。。我建议不如部署一个出来～？有空的时候～？
