### ISSUE TITLE
Contributing to English Documentation

### ISSUE THREAD

**Issue by aalvrz** [FE-Driver/vue-beauty#189]
First of all, great work with this project! I would like to contribute with writing some English documentation for this project. If that is possible, can you provide some guidelines on how to get started?

**Comment by yuu2lee4** [comment]
thanks for your attention, we will do internatinal work when all 2.0 components finished,we welcome your contribute in that time.

**Comment by khawarizmus** [comment]
@yuu2lee4 How is the progress on the English documentation? you have some awesome work here!

**Comment by yuu2lee4** [comment]
Im so busy recently,sorry for having no time to do this.

**Comment by thearabbit** [comment]
+1
