### ISSUE TITLE
Any full migration plans to Vue 2?

### ISSUE THREAD

**Issue by zeroby0** [FE-Driver/vue-beauty#190]
There is an old issue on this, but it's closed. It's mentioned in it that migration will happen in first half of 2017.  
So, any plans for migration? I tried using with Vue 2, but it's buggy.  
Awesome work, btw.

**Comment by yuu2lee4** [comment]
It's ongoing,you can experience it in next branch,swtich to next branch,install the dependencies,excute `npm run package`,then use npm or yarn to install the components package that is on your local file system by '`yarn(npm) add file:/path/to/local/vue-beauty` '.
