### ISSUE TITLE
Error while initializing v-select

### ISSUE THREAD

**Issue by kirtangajjar** [FE-Driver/vue-beauty#192]
Here is the code I used inside a `v-form`
```
<v-form-item label="Type">
    <v-select placeholder="" style="width: 120px;" :options="driver_list" value=""></v-select>
</v-form-item>            
```
and here is the error it showed in console
![screen shot 2017-04-15 at 5 27 13 pm](https://cloud.githubusercontent.com/assets/8456197/25063401/d9c39e18-2200-11e7-958e-a37e32e7e8d6.png)
It says - 
`[Vue warn]: Failed to resolve directive: ref 
(found in <Anonymous> - use the "name" option for better debugging messages.)`

**Comment by yuu2lee4** [comment]
i need more info,maybe you can use the latest version to see  if threre is a problem.

**Comment by kirtangajjar** [comment]
Solved, turns out I had incorrect data passed in options array. Sorry for the trouble.
