### ISSUE TITLE
DatePicker 日期选择框，清除时间后年份报错

### ISSUE THREAD

**Issue by pangxieju** [FE-Driver/vue-beauty#195]
"版本": "2.0.0-alpha2"
![1](https://cloud.githubusercontent.com/assets/18155203/25462972/68f82c52-2b25-11e7-9ada-477ffc6513ef.png)
  日期选择框组件点击清除后确定，再点击输入框 年份显示错误
![2](https://cloud.githubusercontent.com/assets/18155203/25462974/6d2afcbe-2b25-11e7-8616-1b0f7197dd63.png)

**Comment by yuu2lee4** [comment]
更新了。你试一下。。。
