### ISSUE TITLE
Select 选择器 多个在一起的时候会叠加覆盖

### ISSUE THREAD

**Issue by pangxieju** [FE-Driver/vue-beauty#197]
版本: "2.0.0-alpha2"
![4](https://cloud.githubusercontent.com/assets/18155203/25466740/f50a11e4-2b3c-11e7-8662-40d5d3aaf90a.png)
操作下面的 Select 选择器 上面的关闭，一次只显示一个候选列表。

**Comment by yuu2lee4** [comment]
解决
