### ISSUE TITLE
 希望 DatePicker 组件能设置显示位置

### ISSUE THREAD

**Issue by pangxieju** [FE-Driver/vue-beauty#199]
版本: "2.0.0-alpha2"
DatePicker  组件在页面底部的时候无法显示全，希望能设置显示位置。
![tim 20170510151814](https://cloud.githubusercontent.com/assets/18155203/25887288/19433520-3594-11e7-8da8-006ecf91d79b.png)
谢谢！

**Comment by fish-ball** [comment]
+1

**Comment by fish-ball** [comment]
得搞个左对齐或者右对齐的选项，有些靠右的元素尤其是使用范围选择的时候溢出屏幕边缘就没救了。

**Comment by sunriseyuen** [comment]
左对齐或者右对齐的选项  -->改变浏览器的大小时就悲剧了，应该要会自动调整位置比较合适。

**Comment by pangxieju** [comment]
![20170630090843](https://user-images.githubusercontent.com/18155203/27716881-f717929a-5d73-11e7-8550-28bcf2f5fe87.png)
暂时解决办法

**Comment by yuu2lee4** [comment]
现在能自动判断从上面还是下面打开

**Comment by Kuro-P** [comment]
能不能暴露出一个参数，自己把position的样式传过去，自己调整位置，现在带range的dataPicker一不小心组件就跑到页面外了...只能给它放到偏左的地方...
