### ISSUE TITLE
按照官网教程导入部分组件失败

### ISSUE THREAD

**Issue by LeoZlZhang** [FE-Driver/vue-beauty#202]
因为我的项目只要用到部分beauty组件，所以不想全部导入增加web加载时间
按照官网教程导入alert组件
`import { alert } from 'vue-beauty';`
`console.log('debug:',alert);`
`Vue.use(alert);`

但是console输出如下：
![image](https://cloud.githubusercontent.com/assets/9281073/26436019/e63a55a6-4145-11e7-98a1-a5a66383dc55.png)

项目是用VueCLI初始化的, 地址：https://github.com/LeoZlZhang/spring-template-runner-font-end
我刚刚开始接触webpack，看起来可能是配置上的问题，但是google了很久也没有找到解决办法，如问题有不合理之处，请见谅。

**Comment by yuu2lee4** [comment]
你更新一下
