### ISSUE TITLE
DataTable 数据表格的loadData的axios，服务器端返回数据的格式？

### ISSUE THREAD

**Issue by hanjun126** [FE-Driver/vue-beauty#205]
DataTable 数据表格的loadData的axios，服务器端返回数据的格式？

**Comment by yuu2lee4** [comment]
有默认的数据格式。。。{result: array, pageNo: number, pageSize: number}  当然这几个字段名是可以设置的，用axios的好处是，你在then里面得到数据之后，还可以对数据进行加工 然后再return出来
