### ISSUE TITLE
关于DataTable中添加操作列的疑问

### ISSUE THREAD

**Issue by HimiHL** [FE-Driver/vue-beauty#206]
常见的Table里应该可以在每一列添加一个Button来操作，那通过这个DataTable组件应该怎样达到效果呢？
例如：[AntDesign](https://ant.design/docs/pattern/table-cn) 的设计理念之一中的表格，应该有个操作或者更多。
而在目前的DataTable组件中，未找到有类似功能的设置，我应该怎样解决这个问题？

**Comment by yuu2lee4** [comment]
scopedSlot td，通过上面传来的参数可以达到对任意表格里的td进行定制的需求
可以看`特定列使用组件`这个demo
