### ISSUE TITLE
tooltip无法调用

### ISSUE THREAD

**Issue by ghost** [FE-Driver/vue-beauty#209]
无法使用tooltip，希望解答
![image](https://user-images.githubusercontent.com/13042865/27124719-8397435c-5124-11e7-8e45-feea5da14192.png)
无法解析成dom

**Comment by yuu2lee4** [comment]
没问题啊。。。需要更多的信息

**Comment by ghost** [comment]
啊，我看了下源码，
![image](https://user-images.githubusercontent.com/13042865/27216929-60318b3e-52aa-11e7-9265-c05d81aaf07f.png)
这个tooltip指令
![image](https://user-images.githubusercontent.com/13042865/27216951-7da331e0-52aa-11e7-9dc5-21366b6876bc.png)

是不是我用的vue-beauty的版本太低

**Comment by yuu2lee4** [comment]
vue2.x 要用2.0的vue-beauty

**Comment by ghost** [comment]
我的vue是1.0的，所以vue-beauty也是1.0
