### ISSUE TITLE
I begged to support IE(9-10)

### ISSUE THREAD

**Issue by c5ms** [FE-Driver/vue-beauty#216]
My customers has to   use IE  in Venezuela.So we use elementUI now ,because of it suports IE 10  ,but I think vue-beauty is the best UI lib of vueJS .
so I begged to support IE .

**Comment by yuu2lee4** [comment]
i suggest you use iview, it suports IE and it is ant-design style too.

**Comment by c5ms** [comment]
@yuu2lee4  why not IE? only 10

**Comment by yuu2lee4** [comment]
time!I have no time to do it.

**Comment by KrishnaPG** [comment]
IView is not good. Tested it. It has major design problems such as "not driven by data". But their component list is good.
