### ISSUE TITLE
设置dataTable的列宽失败了

### ISSUE THREAD

**Issue by AkatQuas** [FE-Driver/vue-beauty#221]
在columns的 Object里面写了width属性，
浏览器中渲染出来的第一个表头的宽不会按照该width属性展示，而第二个表头的宽按照该属性显示。。
如图
![wechatimg2](https://user-images.githubusercontent.com/24731539/29595396-c0dcf210-87e9-11e7-8182-b338b9d97259.jpeg)
请问，这样的情况怎么解决比较好啊？

**Comment by yuu2lee4** [comment]
因为td th默认设置的不折行，第二个表头虽然设置了正确的宽度，但是由于你内容不折行，有的格子实际宽度跟你设置的宽度是不一样的，第一个表头是根据第二个表头的th的实际宽度来设置的，所以实际上第一个表头的宽度才是现在的实际宽度，解决方法：试试改一下td  th的样式
