### ISSUE TITLE
datatable无数据提示

### ISSUE THREAD

**Issue by putjie** [FE-Driver/vue-beauty#255]
怎么在全局修改datatable的无数据提示字眼
![image](https://user-images.githubusercontent.com/14882234/35141914-97cc8aa2-fd37-11e7-8dfb-29355f9383b3.png)

![image](https://user-images.githubusercontent.com/14882234/35141942-b0b644a4-fd37-11e7-80c6-8ce5c960f371.png)

是只能每个datatable都重写那个emptytext的slot么？

**Comment by yuu2lee4** [comment]
是的

**Comment by putjie** [comment]
~~很痛苦的听到这个，
之前很多默认设置我都是通过扩展来设置
![image](https://user-images.githubusercontent.com/14882234/35144990-2e674c32-fd41-11e7-946b-7af894944169.png)

**Comment by yuu2lee4** [comment]
可以同时提供一个emptytext prop

**Comment by putjie** [comment]
能否提供一个例子，刚入手vue，谢谢

**Comment by yuu2lee4** [comment]
我说的是下个版本 可以提供一个emptytext的prop 这样方便你extends

**Comment by yuu2lee4** [comment]
版本已发布

**Comment by putjie** [comment]
good
