### ISSUE TITLE
window resize should be unhooked when the table is destroyed

### ISSUE THREAD

**Issue by KrishnaPG** [FE-Driver/vue-beauty#258]
I see that the code https://github.com/FE-Driver/vue-beauty/blob/63edb069219925fff35194ab838271a597a4b8b1/vb/components/data-table/data-table.vue#L473 is trying to hook the window `resize` event.

It is using the `addEventListener` to add the hook. But it is not removing the event. When the table component gets destroyed / unmounted, the associated the event listener should be removed, with `removeEventListener` method (since the window may continue to exist in SPA, with different route loaded...)

I see that the code already has `debounceCalculate` method. It can be easily used for add and remove.
````
window.addEventListener('resize', this.debounceCalculate);

beforeDestroy() {
 window.removeEventListener('resize', this.debounceCalculate);
}
````

**Comment by yuu2lee4** [comment]
got it
