### ISSUE TITLE
add "selected" class to the checked rows in Table

### ISSUE THREAD

**Issue by KrishnaPG** [FE-Driver/vue-beauty#259]
To be able to shows checked rows in different style, please add a class `selected` to the `tr` whenever the checkbox is selected for that row.

Remove the class from the `tr` when the checkbox is removed.

This will help with the CSS, such as 
````
tr.selected {
  background: red;
}
````
to highlight the whole checked rows, in case needed.

**Comment by yuu2lee4** [comment]
add `ant-table-row-selected` class
