### ISSUE TITLE
datatable右侧操作能否根据某个字段值来决定是否显示或显示不同按钮

### ISSUE THREAD

**Issue by lysk** [FE-Driver/vue-beauty#282]
datatable右侧操作能否根据某个字段值来决定是否显示或显示不同按钮

**Comment by yuu2lee4** [comment]
当然可以 格子里的内容完全是可定制化的

**Comment by lysk** [comment]
不太习惯配置columns绑定field，那如果我想把多个字段合并在一列显示 怎么做
还有上面那个
能不能有个demo啊 谢谢 @yuu2lee4

**Comment by yuu2lee4** [comment]
columns不一定绑所有field 如果你要自己定制格子内容 也不一定绑真实的field。。可以看 `特定列使用组件` 这个demo
