### ISSUE TITLE
select

### ISSUE THREAD

**Issue by JulesCesar** [FE-Driver/vue-beauty#288]
![Uploading image.png…]()
定位是body  这样默认的定位是不行的。希望改成获取附近的一个节点成为他的父级

**Comment by yuu2lee4** [comment]
popContainer属性了解下？

**Comment by JulesCesar** [comment]
看到了 我试了试 没起作用。我觉得是我用的方法不对貌似？这个我应该怎么在代码里写呢？

**Comment by JulesCesar** [comment]
想在select组件里改 但是看里面代码 怕影响别处就没动。求完整解决方案啊兄弟

**Comment by yuu2lee4** [comment]
show your code

**Comment by JulesCesar** [comment]
<v-row class="import-row">
      <v-col span="4">
        <div class="import-item-name">导入账户：</div>
      </v-col>
      <v-col span="5">
        <v-select style="width: 100%" :data="editOptions.account" @change="accountChange" :optionOnChange="true" >
       
        </v-select>
      </v-col>
    </v-row>

**Comment by JulesCesar** [comment]
<v-row class="import-row">
      <v-col span="4">
        <div class="import-item-name">导入账户：</div>
      </v-col>
      <v-col span="5">
        <v-select style="width: 100%" :data="editOptions.account" @change="accountChange" :optionOnChange="true" >
       
        </v-select>
      </v-col>
    </v-row>

**Comment by JulesCesar** [comment]
<v-row class="import-row">
      <v-col span="4">
        <div class="import-item-name">导入账户：</div>
      </v-col>
      <v-col span="5">
        <v-select style="width: 100%" :data="editOptions.account" @change="accountChange" :optionOnChange="true" >
       
        </v-select>
      </v-col>
    </v-row>

**Comment by JulesCesar** [comment]
` <v-row class="import-row">
      <v-col span="4">
        <div class="import-item-name">导入账户：</div>
      </v-col>
      <v-col span="5">
        <v-select style="width: 100%" :data="editOptions.account" @change="accountChange" :optionOnChange="true" >
       
        </v-select>
      </v-col>
    </v-row>`

**Comment by JulesCesar** [comment]
![image](https://user-images.githubusercontent.com/19618696/38921350-221185ba-4328-11e8-8268-0045da9a1035.png)

**Comment by JulesCesar** [comment]
我需要在select上怎么加popupContainer  function（）{document.body}呢？

**Comment by JulesCesar** [comment]
![image](https://user-images.githubusercontent.com/19618696/38921623-cdfccce0-4328-11e8-97ad-b45d52b9df45.png)
鼠标向下滑动后就成了下图的样子
![image](https://user-images.githubusercontent.com/19618696/38921667-e2808bfc-4328-11e8-9df9-3a03052b7abc.png)

**Comment by yuu2lee4** [comment]
首先在html里 popupContainer要写成 popup-container 
<v-select :popup-container="func"></v-select>

然后在methods里定义func,返回你想要包裹在哪个父级里面，你的这个父级可能也需要设置定位
````javascript
func(){
    return el; //el 是一个dom元素
}
````

**Comment by JulesCesar** [comment]
![image](https://user-images.githubusercontent.com/19618696/38922480-d84976f6-432a-11e8-88d8-f2af2a810351.png)
框都没了。。。

![image](https://user-images.githubusercontent.com/19618696/38922519-f0eaf39c-432a-11e8-8fa4-a9219c19e350.png)

**Comment by yuu2lee4** [comment]
你把方法写在methods里

**Comment by JulesCesar** [comment]
已解决  三克油
