### ISSUE TITLE
v-input-number  小数点后两位的问题

### ISSUE THREAD

**Issue by JulesCesar** [FE-Driver/vue-beauty#289]
![image](https://user-images.githubusercontent.com/19618696/38979860-f0351fd6-43ed-11e8-84c6-333f81cbb771.png)
我是想做个小数点输入两位后。就不让他输入了。就是只能小数点后输入两位。
我打印出来是这个样子的图里的样子 conso出来已经截取了。但是实际输入框里是还可以再继续输入的。。

代码
![image](https://user-images.githubusercontent.com/19618696/38980007-468ed480-43ee-11e8-9554-bd06d70fa13b.png)
![image](https://user-images.githubusercontent.com/19618696/38980032-541b3a30-43ee-11e8-9374-f70e021b4bf3.png)
求方案大神

**Comment by why-no** [comment]
Fixed it by [c1435ec](https://github.com/FE-Driver/vue-beauty/commit/c1435ecbffac24c122f0c00edfcc6c16103edf92)
