### ISSUE TITLE
beforeUpload 上传前检查错误和上传中一起出现的问题

### ISSUE THREAD

**Issue by wchao0615** [FE-Driver/vue-beauty#304]
你好，
  如何在上传前检查错误后，中断上传状态，根据文档return false貌似不管用。谢谢！代码如下：
`beforeUpload(file){
      let isLt3M = file.size / 1024 / 1024 < 3;
      if (!isLt3M) {
        this.$message['error']("请上传小于3MB的图片");
      }
      return isLt3M;
    }`

**Comment by why-no** [comment]
Upload Props 文档有误，请将 beforeUpload 替换为 before-upload，下个版本更新文档。
`<v-upload :name="name" :action="action" :before-upload="beforeUpload" @change="onChange"></v-upload>`
