### ISSUE TITLE
如何在database中加入一列操作按钮

### ISSUE THREAD

**Issue by ISCLOUDX** [FE-Driver/vue-beauty#60]
一般在表格的最后一行都会有对应该行的操作按钮，在与vue-router的配合使用中，没有办法渲染一个
<a v-link={name:'router-name'}>操作</a>
这种情况如何处理呢

**Comment by yuu2lee4** [comment]
是有办法的   明天出个教程

**Comment by ISCLOUDX** [comment]
@yuu2lee4 需要怎么做呢=。=

**Comment by yuu2lee4** [comment]
![111](https://cloud.githubusercontent.com/assets/8046366/20045510/ba51ebda-a4dc-11e6-867f-d22cf68954fc.png)
文档里面有这几个参数的说明哈

**Comment by wyqbailey** [comment]
写的不错

**Comment by ISCLOUDX** [comment]
原来如此 感谢~
