### ISSUE TITLE
datatable组件功能建议

### ISSUE THREAD

**Issue by deboyblog** [FE-Driver/vue-beauty#74]
1. 组件右侧添加 查看/编辑/删除 功能 参考:[ vue-tables](https://jsfiddle.net/matfish2/f5h8xwgn/)
2. 给单行数据加双击事件 参数是对应行数据
3. 头部可加相应操作组 如 : 批量删除(由使用组件方决定删除事件 只传递当前选中行 因现有的组件已经有选中行 参数可以不带) 
新增一行(可以只触发外部事件 不用具备实际功能)
4.页头添加数据筛选功能 同样参考 提议1 的 demo

BUG: 分页部分目前默认不显示每页条数 应该默认显示外部传递的每页条数

**Comment by yuu2lee4** [comment]
功能增强排到2.0

**Comment by yuu2lee4** [comment]
1、已有demo
2、welcome pr
3、可自行在业务层结合getckeckedrows方法实现
4、welcome pr
